[package]
name = "mechyvibes_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
flume = "0.11.1"
once_cell = "1.21.3"
serde = "1.0.228"
serde_json = "1.0"
libc = "0.2.155"
rdev = "0.5.3"
rodio = "0.21.1"
rodio_wav_fix = "0.15.0"
